# Generated by Django 4.2.16 on 2024-12-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObituaryClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obituary_id', models.IntegerField()),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('last_click', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'obituary_clicks',
            },
        ),
    ]
